Repository lv4-project/Woowahan-Tech-Co-learning, pull requests merged in 2019-12, with the labels that each got.

#55 feat: 메인프레임과 유저 프로필 컴포넌트 연결 (#54)
  README.md
  src/frontend/src/App.vue
  src/frontend/src/components/templates/BottomNavigation.vue
  src/frontend/src/components/user/MyPage.vue
  src/frontend/src/components/user/UserProfile.vue
Labels: feature

#49 refactor: 유저 테스트 수정, 유저 생성 파라미터 검증 (#48)
  src/main/java/woowahan/anifarm/tecolearning/user/domain/User.java
  src/main/java/woowahan/anifarm/tecolearning/user/dto/UserInfoDto.java
  src/main/java/woowahan/anifarm/tecolearning/user/dto/UserUpdateDto.java
  src/main/java/woowahan/anifarm/tecolearning/user/exception/UserCreateException.java
  src/test/java/woowahan/anifarm/tecolearning/AbstractWebTestClient.java
  src/test/java/woowahan/anifarm/tecolearning/user/controller/UserControllerTest.java
  src/test/java/woowahan/anifarm/tecolearning/user/domain/UserTest.java
  src/test/resources/woowahan/anifarm/tecolearning/user.xml
Labels: refactor

#70 fix: main layout 깨짐 현상 수정 (#34)
  src/frontend/src/components/Main.vue
Labels: bug

#71 fix: XSS 잠재 보안 위협 해결 (#59)
  src/frontend/package-lock.json
  src/frontend/package.json
Labels: bug

#89 refactor: vue.js에서 request 모듈 중복 import 제거 (#90)
  src/frontend/src/components/user/LoginForm.vue
  src/frontend/src/components/user/SignUpForm.vue
  src/frontend/src/components/user/UserProfile.vue
  src/frontend/src/components/user/UserUpdateForm.vue
  src/frontend/src/main.js
Labels: refactor

#92 feat: 페이지 단위로 Study정보 조회할 수 있도록 백엔드 구현 (#91)
  src/main/java/woowahan/anifarm/tecolearning/auth/advice/LoggedInConfig.java
  src/main/java/woowahan/anifarm/tecolearning/study/controller/StudyApiController.java
  src/main/java/woowahan/anifarm/tecolearning/study/controller/StudySummaryApiController.java
  src/main/java/woowahan/anifarm/tecolearning/study/domain/Study.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/StudyService.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/dto/StudyCreateDto.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/dto/StudyInfoDto.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/dto/StudySummaryDto.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/dto/StudyUpdateDto.java
  src/main/resources/application.properties
  src/test/java/woowahan/anifarm/tecolearning/study/controller/StudyApiControllerTest.java
  src/test/java/woowahan/anifarm/tecolearning/study/controller/StudySummaryApiControllerTest.java
  src/test/java/woowahan/anifarm/tecolearning/study/domain/repository/StudyRepositoryTest.java
  src/test/java/woowahan/anifarm/tecolearning/study/service/StudyServiceTest.java
Labels: feature

#99 feat: PWA 적용 및 install 추가 (#61)
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/public/img/icons/android-chrome-192x192.png
  src/frontend/public/img/icons/android-chrome-512x512.png
  src/frontend/public/img/icons/apple-touch-icon-120x120.png
  src/frontend/public/img/icons/apple-touch-icon-152x152.png
  src/frontend/public/img/icons/apple-touch-icon-180x180.png
  src/frontend/public/img/icons/apple-touch-icon-60x60.png
  src/frontend/public/img/icons/apple-touch-icon-76x76.png
  src/frontend/public/img/icons/apple-touch-icon.png
  src/frontend/public/img/icons/favicon-16x16.png
  src/frontend/public/img/icons/favicon-32x32.png
  src/frontend/public/img/icons/favicon.ico
  src/frontend/public/img/icons/msapplication-icon-144x144.png
  src/frontend/public/img/icons/mstile-150x150.png
  src/frontend/public/img/icons/safari-pinned-tab.svg
  src/frontend/public/index.html
  src/frontend/public/manifest.json
  src/frontend/public/robots.txt
  src/frontend/public/sw.js
  src/frontend/src/main.js
  src/frontend/src/registerServiceWorker.js
  src/main/java/woowahan/anifarm/tecolearning/auth/advice/LoggedInConfig.java
Labels: feature

#102 feat: vuetify theme 추가 (#95)
  src/frontend/src/components/Main.vue
  src/frontend/src/plugins/vuetify.js
Labels: feature

#105 feat: 스터디 발제 & 모집 상세 페이지 프론트 백 연결 (#94)
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/components/Main.vue
  src/frontend/src/components/study/StudyDetail.vue
  src/frontend/src/components/study/StudyGeneration.vue
  src/frontend/src/components/user/LoginForm.vue
  src/frontend/src/components/user/UserUpdateForm.vue
  src/frontend/src/router.js
  src/main/java/woowahan/anifarm/tecolearning/auth/advice/LoggedInInterceptor.java
  src/main/java/woowahan/anifarm/tecolearning/auth/advice/RestControllerExceptionHandler.java
  src/main/java/woowahan/anifarm/tecolearning/study/controller/StudyApiController.java
  src/main/java/woowahan/anifarm/tecolearning/study/domain/Study.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/dto/StudyCreateDto.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/dto/StudyInfoDto.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/dto/StudySummaryDto.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/dto/StudyUpdateDto.java
  src/main/java/woowahan/anifarm/tecolearning/web/WebConfig.java
  src/test/java/woowahan/anifarm/tecolearning/study/controller/StudyApiControllerTest.java
  src/test/java/woowahan/anifarm/tecolearning/study/domain/StudyTest.java
  src/test/java/woowahan/anifarm/tecolearning/study/domain/repository/StudyRepositoryTest.java
Labels: feature

#123 feat: icon 변경 (#122)
  src/frontend/public/img/icons/logo_192x192.png
  src/frontend/public/img/icons/logo_512x512.png
  src/frontend/public/manifest.json
Labels: feature

#116 feat: StudyRecruitment 페이지 무한 스크롤 기능 구현 (#114)
  src/frontend/src/components/study/StudyRecruitment.vue
  src/frontend/src/main.js
Labels: feature

#120 feat: 스터디 참가하기 기능 백엔드 구현 (#117)
  src/main/java/woowahan/anifarm/tecolearning/auth/advice/RestControllerExceptionHandler.java
  src/main/java/woowahan/anifarm/tecolearning/study/controller/StudyApiController.java
  src/main/java/woowahan/anifarm/tecolearning/study/domain/Study.java
  src/main/java/woowahan/anifarm/tecolearning/study/domain/StudyParticipant.java
  src/main/java/woowahan/anifarm/tecolearning/study/domain/StudyParticipantStatus.java
  src/main/java/woowahan/anifarm/tecolearning/study/domain/repository/StudyParticipantRepository.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/StudyService.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/dto/StudyInfoDto.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/exception/InvalidParticipatingRequestException.java
  src/main/java/woowahan/anifarm/tecolearning/user/domain/User.java
  src/test/java/woowahan/anifarm/tecolearning/AbstractWebTestClient.java
  src/test/java/woowahan/anifarm/tecolearning/study/controller/StudyApiControllerTest.java
  src/test/java/woowahan/anifarm/tecolearning/study/domain/StudyTest.java
  src/test/java/woowahan/anifarm/tecolearning/study/service/StudyServiceTest.java
  src/test/java/woowahan/anifarm/tecolearning/user/domain/UserTest.java
  src/test/resources/woowahan/anifarm/tecolearning/study.xml
  src/test/resources/woowahan/anifarm/tecolearning/user.xml
Labels: feature

#133 Fix : github Oauth 수정 (#132)
  src/main/java/woowahan/anifarm/tecolearning/auth/advice/LoggedInConfig.java
  src/main/java/woowahan/anifarm/tecolearning/auth/advice/LoggedInInterceptor.java
  src/main/java/woowahan/anifarm/tecolearning/auth/service/exception/TokenNotFoundException.java
Labels: bug

#140 feat: 스터디 상태에 따라 분류하여 요약 정보 페이지 조회
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/components/study/StudyRecruitment.vue
  src/main/java/woowahan/anifarm/tecolearning/auth/advice/LoggedInConfig.java
  src/main/java/woowahan/anifarm/tecolearning/study/controller/StudySummaryApiController.java
  src/main/java/woowahan/anifarm/tecolearning/study/domain/StudyStatus.java
  src/main/java/woowahan/anifarm/tecolearning/study/domain/repository/StudyRepository.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/StudyService.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/dto/StudySummaryDto.java
  src/test/java/woowahan/anifarm/tecolearning/study/service/StudyServiceTest.java
Labels: bug

#139 fix: github Oauth 수정 (#132)
  src/frontend/src/components/git/GitRedirect.vue
  src/frontend/src/router.js
  src/main/java/woowahan/anifarm/tecolearning/auth/advice/LoggedInConfig.java
  src/main/java/woowahan/anifarm/tecolearning/auth/advice/LoggedInInterceptor.java
  src/main/java/woowahan/anifarm/tecolearning/auth/advice/RestControllerExceptionHandler.java
  src/main/java/woowahan/anifarm/tecolearning/auth/controller/AuthController.java
  src/test/java/woowahan/anifarm/tecolearning/studyoutput/controller/StudyOutputApiControllerTest.java
Labels: bug

#145 feat: StudyOngoingDetail에 스터디 참여 버튼과 request 요청 기능 추가 (#144)
  src/frontend/src/components/study/StudyOngoingDetail.vue
Labels: feature

#156 데이터베이스 h2 -> MySQL (#146)
  build.gradle
  docker/db/mysql/init/init.sql
  docker/docker-compose.yml
  src/main/resources/application.properties
  src/test/java/woowahan/anifarm/tecolearning/TestConfig.java
  src/test/resources/application.properties
Labels: feature

#155 feat : 위치 정보 저장 프론트 백 연결 (#147)
  src/frontend/src/components/map/LocationHistoryBtn.vue
  src/frontend/src/components/map/Map.vue
  src/frontend/src/components/map/MapCard.vue
  src/frontend/src/components/study/StudyOngoingDetail.vue
  src/frontend/src/router.js
  src/main/java/woowahan/anifarm/tecolearning/map/controller/StudyLocationController.java
  src/main/java/woowahan/anifarm/tecolearning/map/dto/StudyLocationDto.java
  src/main/java/woowahan/anifarm/tecolearning/map/service/StudyLocationService.java
Labels: feature

#163 Application properties Profile 설정 (#159)
  .gitignore
  run_new_was.sh
  src/main/resources/application-default.properties
  src/main/resources/application-production.properties
Labels: feature

#168 서버 부팅 스크립트 작성 (#164)
  Jenkinsfile
Labels: feature

#169 fix: -d 옵션을 붙여 컨테이너에서 쉘로 바로 빠져나오도록 수정
  Jenkinsfile
Labels: bug

#167 feat : logout (#162)
  src/frontend/src/components/Main.vue
  src/frontend/src/components/login/LoginBtn.vue
  src/main/java/woowahan/anifarm/tecolearning/auth/controller/AuthController.java
Labels: feature

#166 feat: StudySummaryDto 조회할 때 현재 참여 인원 수도 함께 조회 (#161)
  src/frontend/src/components/study/StudyRecruitment.vue
  src/main/java/woowahan/anifarm/tecolearning/study/controller/StudySummaryApiController.java
  src/main/java/woowahan/anifarm/tecolearning/study/domain/StudyStatus.java
  src/main/java/woowahan/anifarm/tecolearning/study/domain/exception/StudyStatusNotFoundException.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/StudyService.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/dto/StudySummaryDto.java
  src/test/java/woowahan/anifarm/tecolearning/study/controller/StudySummaryApiControllerTest.java
  src/test/java/woowahan/anifarm/tecolearning/study/domain/StudyStatusTest.java
  src/test/java/woowahan/anifarm/tecolearning/study/service/StudyServiceTest.java
Labels: feature

#176 테스트에 사용되는 db가 서비스에 사용하는 db와 동일한 이슈 (#170)
  build.gradle
  src/test/java/woowahan/anifarm/tecolearning/AbstractWebTestClient.java
  src/test/java/woowahan/anifarm/tecolearning/TestConfig.java
  src/test/resources/application.properties
  src/test/resources/application_test.properties
Labels: infra

#173 feat: 스터디 상세 페이지에 참여중인 인원 조회 기능 추가 (#172)
  src/frontend/src/components/study/StudyOngoingDetail.vue
  src/main/java/woowahan/anifarm/tecolearning/study/domain/repository/StudyParticipantRepository.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/StudyParticipantService.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/StudyService.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/dto/StudyDetailInfoDto.java
  src/main/java/woowahan/anifarm/tecolearning/user/domain/User.java
  src/test/java/woowahan/anifarm/tecolearning/study/service/StudyParticipantServiceTest.java
  src/test/java/woowahan/anifarm/tecolearning/study/service/StudyServiceTest.java
  src/test/java/woowahan/anifarm/tecolearning/user/domain/UserTest.java
Labels: feature

#194 feat: 스터디 시작하기 기능 추가
  src/frontend/public/index.html
  src/frontend/src/components/study/StudyOngoingDetail.vue
  src/main/java/woowahan/anifarm/tecolearning/study/controller/StudyApiController.java
  src/main/java/woowahan/anifarm/tecolearning/study/domain/Study.java
  src/main/java/woowahan/anifarm/tecolearning/study/domain/exception/CannotStartStudyException.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/StudyService.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/dto/StudyDetailInfoDto.java
  src/test/java/woowahan/anifarm/tecolearning/AbstractWebTestClient.java
  src/test/java/woowahan/anifarm/tecolearning/study/controller/StudyApiControllerTest.java
  src/test/java/woowahan/anifarm/tecolearning/study/domain/StudyTest.java
  src/test/java/woowahan/anifarm/tecolearning/study/service/StudyServiceTest.java
Labels: feature

#195 fix: 스터디 테스트에서 실패하는 startStudy 오류 수정
  src/main/java/woowahan/anifarm/tecolearning/study/domain/Study.java
  src/test/java/woowahan/anifarm/tecolearning/study/domain/StudyTest.java
Labels: bug

#201 feat: 스터디 완료하기 기능 추가 (#200)
  src/frontend/src/components/study/StudyOngoingDetail.vue
  src/main/java/woowahan/anifarm/tecolearning/study/controller/StudyApiController.java
  src/main/java/woowahan/anifarm/tecolearning/study/domain/Study.java
  src/main/java/woowahan/anifarm/tecolearning/study/domain/exception/CannotFinishStudyException.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/StudyService.java
  src/test/java/woowahan/anifarm/tecolearning/study/controller/StudyApiControllerTest.java
  src/test/java/woowahan/anifarm/tecolearning/study/domain/StudyTest.java
Labels: feature

#192 refactor: UI 소격변 (#191)
  src/frontend/src/assets/login-bg.png
  src/frontend/src/components/Main.vue
  src/frontend/src/components/study/StudyFinished.vue
  src/frontend/src/components/study/StudyGeneration.vue
  src/frontend/src/components/study/StudyOngoing.vue
  src/frontend/src/components/study/StudyRecruitment.vue
  src/frontend/src/components/user/LoginForm.vue
  src/frontend/src/components/user/SignUpForm.vue
  src/frontend/src/components/user/UserProfile.vue
Labels: refactor

#197 feat: 검색 기능 구현(#196)
  src/frontend/src/components/study/StudySearch.vue
  src/frontend/src/components/templates/BottomNavigation.vue
  src/frontend/src/router.js
  src/main/java/woowahan/anifarm/tecolearning/study/controller/StudySummaryApiController.java
  src/main/java/woowahan/anifarm/tecolearning/study/domain/repository/StudyRepository.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/StudyService.java
  src/test/java/woowahan/anifarm/tecolearning/study/controller/StudySummaryApiControllerTest.java
Labels: feature

#203 feat: 설정 서버 활용해서 github 민감정보 가져오기 (#202)
  build.gradle
  src/main/java/woowahan/anifarm/tecolearning/auth/github/GithubClient.java
  src/main/resources/bootstrap.yml
Labels: feature

#205 feat: 스터디 발제 페이지에서 취소 버튼 누르면 dialog 생성 (#204)
  src/frontend/src/components/study/StudyGeneration.vue
Labels: feature

#208 fix: 비로그인시 로그인 페이지로 이동 (#207)
  src/frontend/src/components/Main.vue
  src/frontend/src/components/user/LoginForm.vue
  src/frontend/src/router.js
  src/main/java/woowahan/anifarm/tecolearning/auth/advice/LoggedInConfig.java
  src/main/java/woowahan/anifarm/tecolearning/auth/advice/LoggedInUserArgumentResolver.java
  src/main/java/woowahan/anifarm/tecolearning/user/controller/UserController.java
Labels: bug

#211 민감 정보 설정 서버에 감추기 (#202)
  src/main/resources/application-production.properties
Labels: bug

#209 feat: Snackbar 컴포넌트 추가 & StudyGeneration 컴포넌트에 적용 (#210)
  src/frontend/src/components/Main.vue
  src/frontend/src/components/study/StudyGeneration.vue
  src/frontend/src/components/study/StudySearch.vue
  src/frontend/src/components/templates/SnackBar.vue
Labels: feature

#213 데이터베이스 서버 분리 (#212)
  Jenkinsfile
  src/main/resources/application-default.properties
  src/main/resources/application-production.properties
Labels: infra

#219 설정 서버 분리 (#218)
  src/main/resources/bootstrap.yml
Labels: infra

#217 feat: 스터디 인원이 가득 찼을 경우 참여 불가능 (#188)
  src/frontend/src/components/study/StudyOngoingDetail.vue
  src/main/java/woowahan/anifarm/tecolearning/study/domain/Study.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/StudyService.java
  src/main/java/woowahan/anifarm/tecolearning/study/service/exception/CannotParticipateException.java
  src/test/java/woowahan/anifarm/tecolearning/study/domain/StudyTest.java
Labels: feature

#224 feat: Skeleton loader 추가 (#223)
  src/frontend/src/components/study/StudyCard.vue
  src/frontend/src/components/study/StudyCardsTemplateByStatus.vue
  src/frontend/src/components/study/StudySearch.vue
Labels: feature

#230 feat: 활동내역 링크 추가 (#229)
  src/frontend/src/components/study/StudyGeneration.vue
  src/frontend/src/components/user/UserProfile.vue
Labels: feature

#232 빌드 서버 분리 (#231)
  Jenkinsfile
  deploy.sh
  run_new_was.sh
Labels: infra
